version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: backend_server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/products?schema=public

  db:
    image: postgres:14-alpine
    container_name: products_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=products
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata: